name: knights-ecomm-be CI

on: [push, pull_request]

env:
  TEST_DB_HOST: ${{secrets.TEST_DB_HOST}}
  TEST_DB_PORT: ${{secrets.TEST_DB_PORT}}
  TEST_DB_USER: ${{secrets.TEST_DB_USER}}
  TEST_DB_PASS: ${{secrets.TEST_DB_PASS}}
  TEST_DB_NAME: ${{secrets.TEST_DB_NAME}}
<<<<<<< HEAD
<<<<<<< HEAD
=======
  HOST: ${{secrets.HOST}}
  AUTH_EMAIL: ${{secrets.AUTH_EMAIL}}
  AUTH_PASSWORD: ${{secrets.AUTH_PASSWORD}}
>>>>>>> 2b118c3 (Implemented user registration feature with input validation, password hashing, and database integration)
=======
>>>>>>> c7b1dc4 (fix(user registration): resolve registration bug)

jobs:
  build-lint-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and Prettier
        run: npm run lint

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
